### ISSUE TITLE
TypeError: Cannot set property 'torrentFileName' of undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1030]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** All

From our telemetry error logs, we picked up this error. It occurred 4 times today.

```
Processes: window, platforms: darwin linux win32, versions: 0.16.0 0.17.1 0.17.2
TypeError: Cannot set property 'torrentFileName' of undefined
    at TorrentController.torrentFileSaved (.../build/renderer/controllers/torrent-controller.js:141:36)
    at EventEmitter.<anonymous> (.../build/renderer/main.js:402:32)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by Flet** [comment]
Are you just looking for some more defensive code to catch these bad states?
