### ISSUE TITLE
TypeError: Error processing argument at index 0, conversion failure from undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1035]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** Mac, Windows

From our telemetry error logs, we picked up this error. It occurred 27 times today.

```
Processes: main window, platforms: darwin win32, versions: 0.15.0 0.16.0 0.17.1 0.17.2
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at click (.../build/renderer/controllers/torrent-list-controller.js:217:54)
    at CallbacksRegistry.apply (/Applications/WebTorrent.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by Goldob** [comment]
How to reproduce:

1. Disable internet connection.
2. Add a new torrent by magnet link.
3. Right click it, then _Copy Magnet Link to Clipboard_.

The problem is that we don't write `torrentSummary.magnetURI` until we receive full torrent metadata - even if it was explicitly provided by the user.
