### ISSUE TITLE
TypeError: Cannot read property 'mediaSessionId' of undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1037]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** All

From our telemetry error logs, we picked up this error. It occurred 35 times today.

```
Processes: window, platforms: darwin linux win32, versions: pre-0.12 0.16.0 0.17.1 0.17.2
TypeError: Cannot read property 'mediaSessionId' of undefined
    at MediaController.sessionRequest (.../node_modules/castv2-client/lib/controllers/media.js:88:44)
    at MediaController.stop (.../node_modules/castv2-client/lib/controllers/media.js:107:8)
    at DefaultMediaReceiver.stop (.../node_modules/castv2-client/lib/senders/default-media-receiver.js:42:19)
    at .../node_modules/chromecasts/index.js:185:11
    at apply (.../node_modules/thunky/index.js:16:28)
    at .../node_modules/thunky/index.js:27:3
    at EventEmitter.player.stop (.../node_modules/chromecasts/index.js:183:7)
    at Object.stop (.../build/renderer/lib/cast.js:162:16)
    at Object.stop (.../build/renderer/lib/cast.js:429:12)
    at PlaybackController.closePlayer (.../build/renderer/controllers/playback-controller.js:323:12)
```

**Comment by Goldob** [comment]
https://github.com/mafintosh/chromecasts/issues/23

**Comment by smolleyes** [comment]
hi

now way to fix this !! ?

thanks
