### ISSUE TITLE
npm ERR! when Package the app

### ISSUE THREAD

**Issue by KingMaxer** [webtorrent/webtorrent-desktop#1211]
**What operating system and version?**
Windows10 1703 64-bit
**What actually happened?**
npm ERR! when Package the app,build package failed.

Hello,
I use the latest source code to package the app,but there is a npm ERR!
I tried to build win32 package but failed，but `npm start `launched the desktop application well.
I don't know how to solve the problem. Who can help me ?
The logs list below:

`C:\Users\simpl\webtorrent-desktop>npm start

> webtorrent-desktop@0.18.0 start C:\Users\simpl\webtorrent-desktop
> npm run build && electron .

> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

init: 5674.629ms

C:\Users\simpl\webtorrent-desktop>npm run package

> webtorrent-desktop@0.18.0 package C:\Users\simpl\webtorrent-desktop
> node ./bin/package.js

Reinstalling node_modules...

> bufferutil@3.0.2 install C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.1
prebuild-install info looking for local prebuild @ prebuilds\bufferutil-v3.0.2-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ D:\nodejs\node_cache\_prebuilds\https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v57-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ D:\nodejs\node_cache\_prebuilds\https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil\build\Release\bufferutil.node
prebuild-install info unpack required C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil\build\Release\bufferutil.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> electron-chromedriver@1.7.1 install C:\Users\simpl\webtorrent-desktop\node_modules\electron-chromedriver
> node ./download-chromedriver.js

> electron@1.6.0 postinstall C:\Users\simpl\webtorrent-desktop\node_modules\electron
> node install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> webtorrent-desktop@0.18.0 prepublish C:\Users\simpl\webtorrent-desktop
> npm run build

> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules\appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 895 packages in 238.086s
removed 1 package and moved 1 package in 6.071s
Nuking dist/ and build/...
Build: Transpiling to ES5...

> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

Build: Transpiled to ES5.
Mac: Packaging electron...
Downloading tmp-5244-1-SHASUMS256.txt-1.6.0
[============================================>] 100.0% of 4.43 kB (4.43 kB/s)
Packaging app for platform darwin x64 using electron v1.6.0
Command failed: npm prune --production
npm ERR! May not delete: C:\Users\simpl\AppData\Local\Temp\electron-packager\darwin-x64\WebTorrent-darwin-x64\Electron.app\Contents\Resources\app\node_modules\.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2017-07-25T15_07_54_994Z-debug.log
Downloading tmp-5244-2-electron-v1.6.0-win32-ia32.zip
[============================================>] 100.0% of 43.1 MB (4.93 MB/s)
Packaging app for platform win32 ia32 using electron v1.6.0
Command failed: npm prune --production
npm ERR! May not delete: C:\Users\simpl\AppData\Local\Temp\electron-packager\win32-ia32\WebTorrent-win32-ia32\resources\app\node_modules\.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2017-07-25T15_11_10_902Z-debug.log
Downloading tmp-5244-3-electron-v1.6.0-linux-ia32.zip
[============================================>] 100.0% of 48.85 MB (4.65 MB/s)
Packaging app for platform linux ia32 using electron v1.6.0
Command failed: npm prune --production
npm ERR! May not delete: C:\Users\simpl\AppData\Local\Temp\electron-packager\linux-ia32\WebTorrent-linux-ia32\resources\app\node_modules\.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2017-07-25T15_14_25_839Z-debug.log

C:\Users\simpl\webtorrent-desktop>npm run package -- win32 --sign

> webtorrent-desktop@0.18.0 package C:\Users\simpl\webtorrent-desktop
> node ./bin/package.js "win32" "--sign"

Reinstalling node_modules...

> bufferutil@3.0.2 install C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.1
prebuild-install info looking for local prebuild @ prebuilds\bufferutil-v3.0.2-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ D:\nodejs\node_cache\_prebuilds\https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v57-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ D:\nodejs\node_cache\_prebuilds\https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil\build\Release\bufferutil.node
prebuild-install info unpack required C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil\build\Release\bufferutil.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> electron-chromedriver@1.7.1 install C:\Users\simpl\webtorrent-desktop\node_modules\electron-chromedriver
> node ./download-chromedriver.js

> electron@1.6.0 postinstall C:\Users\simpl\webtorrent-desktop\node_modules\electron
> node install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> webtorrent-desktop@0.18.0 prepublish C:\Users\simpl\webtorrent-desktop
> npm run build

> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules\appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 892 packages in 251.988s
up to date in 5.897s
Nuking dist/ and build/...
Build: Transpiling to ES5...

> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

Build: Transpiled to ES5.
Windows: Packaging electron...
Packaging app for platform win32 ia32 using electron v1.6.0
Command failed: npm prune --production
npm ERR! May not delete: C:\Users\simpl\AppData\Local\Temp\electron-packager\win32-ia32\WebTorrent-win32-ia32\resources\app\node_modules\.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2017-07-25T15_24_06_480Z-debug.log`

[2017-07-25T15_11_10_902Z-debug.log.txt](https://github.com/webtorrent/webtorrent-desktop/files/1174169/2017-07-25T15_11_10_902Z-debug.log.txt)

**Comment by KingMaxer** [comment]
The above problem has been solved .
Solution to the problem: use Node.js v6.11.1 LTS , do not the latest v8.2.1 version.

Although the LTS version of the Node.js can compile the software, but there will still be errors in the software compilation process.
The logs list below:

C:\Users\simpl\webtorrent-desktop>npm run package -- win32 --sign

> webtorrent-desktop@0.18.0 package C:\Users\simpl\webtorrent-desktop
> node ./bin/package.js "win32" "--sign"

Reinstalling node_modules...
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> bufferutil@3.0.2 install C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.1
prebuild-install info looking for local prebuild @ prebuilds\bufferutil-v3.0.2-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ D:\nodejs\node_cache\_prebuilds\https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v48-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ D:\nodejs\node_cache\_prebuilds\https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v48-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil\build\Release\bufferutil.node
prebuild-install info unpack required C:\Users\simpl\webtorrent-desktop\node_modules\bufferutil\build\Release\bufferutil.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> electron-chromedriver@1.7.1 install C:\Users\simpl\webtorrent-desktop\node_modules\electron-chromedriver
> node ./download-chromedriver.js


> electron@1.6.0 postinstall C:\Users\simpl\webtorrent-desktop\node_modules\electron
> node install.js


> webtorrent-desktop@0.18.0 prepublish C:\Users\simpl\webtorrent-desktop
> npm run build


> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.4.3 (node_modules\appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
- lodash@4.17.4 node_modules\xml2js\node_modules\lodash
Nuking dist/ and build/...
Build: Transpiling to ES5...

> webtorrent-desktop@0.18.0 build C:\Users\simpl\webtorrent-desktop
> buble src --output build

Build: Transpiled to ES5.
Windows: Packaging electron...
Downloading tmp-3924-0-electron-v1.6.0-win32-ia32.zip
[============================================>] 100.0% of 43.1 MB (5.39 MB/s)
Packaging app for platform win32 ia32 using electron v1.6.0
Packaging app for platform win32 x64 using electron v1.6.0
Windows: Packaged electron. C:\Users\simpl\webtorrent-desktop\dist\WebTorrent-win32-ia32,C:\Users\simpl\webtorrent-desktop\dist\WebTorrent-win32-x64
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\authenticode.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at C:\Users\simpl\webtorrent-desktop\bin\package.js:387:40
    at C:\Users\simpl\webtorrent-desktop\node_modules\electron-packager\index.js:258:7
    at end (C:\Users\simpl\webtorrent-desktop\node_modules\run-series\index.js:8:15)
    at done (C:\Users\simpl\webtorrent-desktop\node_modules\run-series\index.js:11:10)
    at each (C:\Users\simpl\webtorrent-desktop\node_modules\run-series\index.js:16:43)
    at C:\Users\simpl\webtorrent-desktop\node_modules\electron-packager\common.js:297:7
    at FSReqWrap.CB [as oncomplete] (C:\Users\simpl\webtorrent-desktop\node_modules\electron-packager\node_modules\fs-extra\lib\remove\rimraf.js:57:5)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package" "--" "win32" "--sign"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! webtorrent-desktop@0.18.0 package: `node ./bin/package.js "win32" "--sign"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webtorrent-desktop@0.18.0 package script 'node ./bin/package.js "win32" "--sign"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webtorrent-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/package.js "win32" "--sign"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webtorrent-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webtorrent-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\simpl\webtorrent-desktop\npm-debug.log

**Comment by DiegoRBaquero** [comment]
Why do you use the --sign param?

**Comment by KingMaxer** [comment]
Thank you very much！@DiegoRBaquero
I see. The software signature can only be completed by the owner.
