### ISSUE TITLE
Error packaging Linux .deb 

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent-desktop#1255]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.18.0
**What operating system and version?**
Win 10
**What did you do?**
Trying to package to a .deb file

I can succesfully package .exe and .zip linux files. But trying to package to a .deb file I get this:
`path.js:725
  dirname: function dirname(path) {
                           ^

RangeError: Maximum call stack size exceeded
    at Object.dirname (path.js:725:28)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:33)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
    at addParentDirs (C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\nobin-debian-installer\index.js:
226:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webtorrent-desktop@0.18.0 package: `node ./bin/package.js "linux" "--package=deb"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webtorrent-desktop@0.18.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ivan\AppData\Roaming\npm-cache\_logs\2017-10-17T15_40_46_292Z-debug.log`

And in the logfile:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ivan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package',
1 verbose cli   '--',
1 verbose cli   'linux',
1 verbose cli   '--package=deb' ]
2 info using npm@5.4.2
3 info using node@v8.5.0
4 verbose run-script [ 'prepackage', 'package', 'postpackage' ]
5 info lifecycle webtorrent-desktop@0.18.0~prepackage: webtorrent-desktop@0.18.0
6 info lifecycle webtorrent-desktop@0.18.0~package: webtorrent-desktop@0.18.0
7 verbose lifecycle webtorrent-desktop@0.18.0~package: unsafe-perm in lifecycle true
8 verbose lifecycle webtorrent-desktop@0.18.0~package: PATH: C:\Users\ivan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Codebox\BitMeterOS;C:\Users\ivan\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Program Files\GPAC;C:\auto\casperjs\bin;C:\auto\phantomjs;C:\Users\ivan\AppData\Roaming\npm
9 verbose lifecycle webtorrent-desktop@0.18.0~package: CWD: C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop
10 silly lifecycle webtorrent-desktop@0.18.0~package: Args: [ '/d /s /c', 'node ./bin/package.js "linux" "--package=deb"' ]
11 silly lifecycle webtorrent-desktop@0.18.0~package: Returned: code: 1  signal: null
12 info lifecycle webtorrent-desktop@0.18.0~package: Failed to exec package script
13 verbose stack Error: webtorrent-desktop@0.18.0 package: `node ./bin/package.js "linux" "--package=deb"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ivan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ivan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid webtorrent-desktop@0.18.0
15 verbose cwd C:\Users\ivan\Desktop\divx\wtdesk\webtorrent-desktop
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ivan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "package" "--" "linux" "--package=deb"
18 verbose node v8.5.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error webtorrent-desktop@0.18.0 package: `node ./bin/package.js "linux" "--package=deb"`
22 error Exit status 1
23 error Failed at the webtorrent-desktop@0.18.0 package script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
Any idea?

**Comment by Ciao121** [comment]
It builds correctly if packaged under debian.
