### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Albermonte** [webtorrent/webtorrent-desktop#1277]
**What operating system and version?** Windows

**What did you do?** Just build the package

I've tested it on my windows 10 and only sometimes it works, also tested on AppVeyor and got the same error.

Now I can't delete the electron.exe on my pc.

```
> > webtorrent-desktop@0.18.0 package C:\projects\webtorrent-desktop
> node ./bin/package.js
C:\projects\webtorrent-desktop\bin\package.js:371
  let CERT_PATH
  ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package" "--win32" "--package=exe"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! webtorrent-desktop@0.18.0 package: `node ./bin/package.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webtorrent-desktop@0.18.0 package script 'node ./bin/package.js'.
npm ERR! This is most likely a problem with the webtorrent-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/package.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webtorrent-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls webtorrent-desktop
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\webtorrent-desktop\npm-debug.log
Command exited with code 1
```

**Comment by KingMaxer** [comment]
Meybe that is a problem about Node.js version.
Try to use Node.js V6.11 then you can  build the package.
