### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1314]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.19

**What operating system and version?**

All

**What did you do?**

```
Processes: window, platforms: darwin linux win32, versions: 0.18.0 0.19.0
TypeError: Cannot read property 'map' of undefined
    at TorrentListController.resumePausedTorrents (...\build\renderer\controllers\torrent-list-controller.js:187:38)
    at EventEmitter.<anonymous> (...\build\renderer\main.js:391:76)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

This is the top error in the telemetry logs since the release of 0.19. Appears to be affecting A LOT of users. @codealchemist - any ideas?

**Comment by codealchemist** [comment]
Yay! Thanks!
