### ISSUE TITLE
Electron 4 support

### ISSUE THREAD

**Issue by qarkai** [webtorrent/webtorrent-desktop#1564]
**What version of WebTorrent Desktop?**
0.20.0 (from https://aur.archlinux.org/packages/webtorrent-desktop/)

**What operating system and version?**
Arch Linux

**What did you do?**
Upgraded to electron-4.1.1

**What did you expect to happen?**
webtorrent-desktop started

**What actually happened?**
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/usr/lib/webtorrent-desktop/build/main/index.js:41:20)
    at Object.<anonymous> (/usr/lib/webtorrent-desktop/build/main/index.js:228:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/webtorrent-desktop/index.js:1:156)

```

**Comment by qarkai** [comment]
Switch to branch greenkeeper/electron-4.1.4 doesn't help.

**Comment by vitlav** [comment]
`$ sed -i -e "s/shouldQuit = app.makeSingleInstance(\(.*\))/shouldQuit = !app.requestSingleInstanceLock()/" src/main/index.js`

**Comment by feross** [comment]
This is being handled in this PR: https://github.com/webtorrent/webtorrent-desktop/pull/1590
