### ISSUE TITLE
doesnt work -- npm install ; npm start ; 

### ISSUE THREAD

**Issue by didlie** [webtorrent/webtorrent-desktop#1630]
App threw an error during load
C:\Users\TezosDeveloper\Documents\GitHub\webtorrent-desktop\index.js:2
Terminate batch job (Y/N)? Terminate batch job (Y/N)?
          ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at loadApplicationPackage (C:\Users\TezosDeveloper\Documents\GitHub\webtorrent-desktop\node_modules\electron\dist\resources\default_app.asar\main.js:287:12)
    at Object.<anonymous> (C:\Users\TezosDeveloper\Documents\GitHub\webtorrent-desktop\node_modules\electron\dist\resources\default_app.asar\main.js:329:5)
    at Object.<anonymous> (C:\Users\TezosDeveloper\Documents\GitHub\webtorrent-desktop\node_modules\electron\dist\resources\default_app.asar\main.js:366:3)

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by feross** [comment]
Duplicate https://github.com/webtorrent/webtorrent-desktop/issues/1600
