### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by thevirajshelke** [webtorrent/webtorrent-desktop#1687]
**What version of this package are you using?** 
master branch

**What operating system, Node.js, and npm version?**
Linux OS - Ubuntu 18.04.3
Node version - v12.6.0
Npm version - v6.11.3

**What happened?**
- I did a `git clone` & then did a `npm install` after which I am getting the following error
```bash
npm ERR! code 128
npm ERR! Command failed: git checkout cddd2872f0020ecf5016f326cf5e58c965eef52a
npm ERR! fatal: reference is not a tree: cddd2872f0020ecf5016f326cf5e58c965eef52a
npm ERR! 
npm WARN tar ENOENT: no such file or directory, open '/home/thevirajshelke/webtorrent-desktop/node_modules/.staging/electron-winstaller-cc9cd11c/vendor/Squirrel.pdb'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thevirajshelke/.npm/_logs/2019-09-12T14_39_28_471Z-debug.log
```

**What did you expect to happen?**
- All the npm packages are supposed to install successfully

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by thevirajshelke** [comment]
@feross Yep It's working fine now. :+1: 
I was developing an electron application too by combining Angular and Electron frameworks.
I just thought of studying your code as well hence cloned your project yesterday. That's when I came across the issue.

Cheers :)

**Comment by thevirajshelke** [comment]
@feross can you check what's wrong with `npm run package` as well? 

```bash
> webtorrent-desktop@0.20.0 package /home/thevirajshelke/webtorrent-desktop
> node ./bin/package.js

/home/thevirajshelke/webtorrent-desktop/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/thevirajshelke/webtorrent-desktop/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/thevirajshelke/webtorrent-desktop/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/thevirajshelke/webtorrent-desktop/src/config.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/thevirajshelke/webtorrent-desktop/bin/package.js:18:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webtorrent-desktop@0.20.0 package: `node ./bin/package.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webtorrent-desktop@0.20.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thevirajshelke/.npm/_logs/2019-09-13T07_32_51_640Z-debug.log
```

I tried reinstalling it again as well! Please do check.
