### ISSUE TITLE
0.21.0 Windows 10 x64 didn't created an item in start menu.

### ISSUE THREAD

**Issue by urza** [webtorrent/webtorrent-desktop#1745]
**What version of WebTorrent Desktop are you using?**
0.21.0

**What operating system and version?**
Windows 10 Pro x64 build 17763

**What happened?**
After downloading and installing WebTorrent desktop client, there is no WebTorrent item in Start menu neither shortcut on Desktop. Typing "webtorrent" to start menu search only finds the install file. It is not possible to start the WebTorrent easily.

**What did you expect to happen?**
Create item in Start menu.

**Comment by hicom150** [comment]
I could not reproduce the problem in `Windows 10 Enterprise Evaluation` 😓

![VirtualBox_MSEdge - Win10_22_11_2019_21_55_58](https://user-images.githubusercontent.com/715354/69460154-b2c6e200-0d73-11ea-9171-c1b06400305e.png)
![VirtualBox_MSEdge - Win10_22_11_2019_21_55_21](https://user-images.githubusercontent.com/715354/69460162-ba868680-0d73-11ea-803a-9018389cc943.png)

@urza could you try again and check if there is any error message during installation?

**Comment by gsabetta** [comment]
![image](https://user-images.githubusercontent.com/55319644/69472383-35f23300-0d88-11ea-9cc7-342556ed213a.png)

I was able to reproduce it. Clicking the installer launches the application like it was portable, it also always open like is the very first run.

I'm running Windows 10 version 1903 (OS Build 18362.476)

**Comment by ANDiTKO** [comment]
I also got this issue. Same as @gsabetta the installer launches as a portable app, and nothing is installed. I even tried to run the installer as an Administrator, but that did not help.
I'm on Windows 10 Pro build 1803

Is there an alternative way to install the app? Maybe copy-paste files. Or extract an archive manually without the installer?

**Comment by hicom150** [comment]
In order to get better debug info, could you please paste here the content this file? 😉

```
C:\Users\your_user_name\AppData\Local\WebTorrent\SquirrelSetup.log
```

**Comment by AlopeLago** [comment]
I too had this problem when installing. Have "installed" it about 4 times now.


Here's the squirrelsetup.log

> 2019-11-26 12:05:06> Program: Starting Squirrel Updater: --createShortcut WebTorrent.exe
2019-11-26 12:05:10> Program: Starting Squirrel Updater: --checkForUpdate https://webtorrent.io/desktop/update?version=0.21.0&platform=win32&sysarch=x64
2019-11-26 12:05:10> Program: Fetching update information, downloading from https://webtorrent.io/desktop/update?version=0.21.0&platform=win32&sysarch=x64
2019-11-26 12:05:10> CheckForUpdateImpl: Generated new staging user ID: 8a01339b-484b-5a0a-8789-36fefaf0f895
2019-11-26 12:05:10> CheckForUpdateImpl: Downloading RELEASES file from https://webtorrent.io/desktop/update?version=0.21.0&platform=win32&sysarch=x64
2019-11-26 12:05:10> FileDownloader: Downloading url: https://webtorrent.io/desktop/update/RELEASES?version=0.21.0&platform=win32&sysarch=x64&id=WebTorrent&localVersion=0.21.0&arch=amd64

**Comment by hicom150** [comment]
The log file looks correct to me as it is calling to `--createShortcut` correctly.

> 2019-11-26 12:05:06> Program: Starting Squirrel Updater: --createShortcut WebTorrent.exe

Could you try to execute this command to check if it throws any error?

```
C:\Users\your_user_name\AppData\Local\WebTorrent\Update.exe --createShortcut=WebTorrent.exe
```

**Comment by mohannadize** [comment]
I have the same problem

here is what's in the log file

```
2019-11-29 21:09:44> Program: Starting Squirrel Updater: --checkForUpdate https://webtorrent.io/desktop/update?version=0.21.0&platform=win32&sysarch=x64
2019-11-29 21:09:44> Program: Fetching update information, downloading from https://webtorrent.io/desktop/update?version=0.21.0&platform=win32&sysarch=x64
2019-11-29 21:09:44> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\mohan\AppData\Local\Temp\.squirrel-lock-074FA245760B0898A78E77B2F760723A7F89DD02: System.IO.IOException: The process cannot access the file 'C:\Users\mohan\AppData\Local\Temp\.squirrel-lock-074FA245760B0898A78E77B2F760723A7F89DD02' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2019-11-29 21:09:45> CheckForUpdateImpl: Generated new staging user ID: 0503db0b-5052-5745-af7f-b4df46bbdc02
2019-11-29 21:09:45> CheckForUpdateImpl: Downloading RELEASES file from https://webtorrent.io/desktop/update?version=0.21.0&platform=win32&sysarch=x64
2019-11-29 21:09:45> FileDownloader: Downloading url: https://webtorrent.io/desktop/update/RELEASES?version=0.21.0&platform=win32&sysarch=x64&id=WebTorrent&localVersion=0.21.0&arch=amd64
```

**Comment by AlopeLago** [comment]
When I ran that second command it created a shortcut so seems to have solved the issue. Here's the new log.

> 2019-12-01 12:56:18> Program: Starting Squirrel Updater: --createShortcut WebTorrent.exe
2019-12-01 12:56:18> ApplyReleasesImpl: About to create shortcuts for WebTorrent.exe, rootAppDir C:\Users\Kyle\AppData\Local\WebTorrent
2019-12-01 12:56:18> ApplyReleasesImpl: Creating shortcut for WebTorrent.exe => C:\Users\Kyle\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WebTorrent\WebTorrent.lnk
2019-12-01 12:59:09> Program: Starting Squirrel Updater: --createShortcut=WebTorrent.exe
2019-12-01 12:59:09> ApplyReleasesImpl: About to create shortcuts for WebTorrent.exe, rootAppDir C:\Users\Kyle\AppData\Local\WebTorrent
2019-12-01 12:59:09> ApplyReleasesImpl: Creating shortcut for WebTorrent.exe => C:\Users\Kyle\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WebTorrent\WebTorrent.lnk
2019-12-01 12:59:09> ApplyReleasesImpl: About to save shortcut: C:\Users\Kyle\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WebTorrent\WebTorrent.lnk (target C:\Users\Kyle\AppData\Local\WebTorrent\WebTorrent.exe, workingDir C:\Users\Kyle\AppData\Local\WebTorrent\app-0.21.0, args , toastActivatorCSLID 94e31f7a-4ff2-5f29-8fbc-da8d22ea3031)
2019-12-01 12:59:09> ApplyReleasesImpl: Creating shortcut for WebTorrent.exe => C:\Users\Kyle\Desktop\WebTorrent.lnk
2019-12-01 12:59:09> ApplyReleasesImpl: About to save shortcut: C:\Users\Kyle\Desktop\WebTorrent.lnk (target C:\Users\Kyle\AppData\Local\WebTorrent\WebTorrent.exe, workingDir C:\Users\Kyle\AppData\Local\WebTorrent\app-0.21.0, args , toastActivatorCSLID 94e31f7a-4ff2-5f29-8fbc-da8d22ea3031)
2019-12-01 12:59:09> ApplyReleasesImpl: Examining Pin: Discord.lnk
2019-12-01 12:59:09> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2019-12-01 12:59:09> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-12-01 12:59:09> ApplyReleasesImpl: Examining Pin: Steam.lnk

**Comment by hicom150** [comment]
Great! Thank you for your feedback 👍
It seems that the problem could be located in [this](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/squirrel-win32.js) file, so I would try to investigate deeper if I can find what is failing 😉

**Comment by hicom150** [comment]
I have created #1754 to try fix this issue. If anyone could test it in a Windows machine, the help would be appreciated 😉

**Comment by RecoX** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/55319644/69472383-35f23300-0d88-11ea-9cc7-342556ed213a.png)
> 
> I was able to reproduce it. Clicking the installer launches the application like it was portable, it also always open like is the very first run.
> 
> I'm running Windows 10 version 1903 (OS Build 18362.476)

Same problem here!!

**Comment by ArielLahiany** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/55319644/69472383-35f23300-0d88-11ea-9cc7-342556ed213a.png)
> 
> I was able to reproduce it. Clicking the installer launches the application like it was portable, it also always open like is the very first run.
> 
> I'm running Windows 10 version 1903 (OS Build 18362.476)

17/4/2020: Windows 10 Pro, same problem.

**Comment by yepyepyep4711** [comment]
I'm not sure this is related, but here on win7 64bit I can't seem to be able to install the new version either. Uninstalling 0.20.0 leaves the shortcut in the start menu. Which in my case is useful, because as for the others here, installing 0.21.0 doesn't create one. So at least after installation the old shortcut starts working again.

BUT the confusing part is that when I launch webtorrent using said shortcut (that wasn't working anymore after uninstalling 0.20.0, I checked), then what starts still says BETA and version 0.20.0, regardless of the fact that it was installed with WebTorrentSetup-v0.21.0.exe

**Comment by kiruh** [comment]
I have the same issue

**Comment by aashutoshrathi** [comment]
@kiruh answer helped me.
Found `C:\Users\<user>\AppData\` in the excluded folders for Search in Windows Search Settings.

**Comment by feross** [comment]
@georgir The issue has been resolved and released in the latest version of WebTorrent
