### ISSUE TITLE
VLC playing not working

### ISSUE THREAD

**Issue by Mracobes9** [webtorrent/webtorrent-desktop#1807]
**What version of WebTorrent Desktop are you using?**
Version 0.21.0-3

**What operating system and version?**
Manjaro 20.0

**What happened?**
Torrent doesn't play in VLC player.  I got a error 
```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at normalizeSpawnArguments (child_process.js:414:11)
    at Object.spawn (child_process.js:547:16)
    at spawnExternal (/usr/lib/webtorrent-desktop/build/main/external-player.js:55:13)
    at Object.spawn (/usr/lib/webtorrent-desktop/build/main/external-player.js:25:36)
    at IpcMainImpl.<anonymous> (/usr/lib/webtorrent-desktop/build/main/ipc.js:264:26)
    at IpcMainImpl.emit (events.js:210:5)
    at IpcMainImpl.ipc.emit (/usr/lib/webtorrent-desktop/build/main/ipc.js:304:18)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3851:15)
    at WebContents.emit (events.js:210:5) {
  code: 'ERR_INVALID_ARG_VALUE'
}

```
**What did you expect to happen?**
Torrent video must open in vlc.

**Comment by keshamin** [comment]
I have the same issue.
