### ISSUE TITLE
Apple Silicon Support for Mac

### ISSUE THREAD

**Issue by 007NewBieCoder** [webtorrent/webtorrent-desktop#1907]
**What version of WebTorrent Desktop are you using?**
WebTorrent Desktop Version 0.24.0 (0.108.6) Mac
**What operating system and version?**
MacOS Big Sur 11.0.1; Macbook Pro M1 Chip
**What problem do you want to solve?**
Update the App to support Apple Silicon Natively
**What do you think is the correct solution to this problem?**
The app runs a bit slow and also the torrent files played using the player skips frames from time to time! Updating the app will allow it to use the full power of the laptop and greatly optimise the app. It will also provide a better experience of using the app too.

**Comment by SethuSenthil** [comment]
This should get more attention! The version of electron implemented already supports building for Apple Silicon, the potential issues could be the dependencies

**Comment by brasilikum** [comment]
Yes, when I try to compile on arm64, `chromedriver` fails:

```
error /Users/georghartmann/Downloads/webtorrent-desktop/node_modules/electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments: 
Directory: /Users/georghartmann/Downloads/webtorrent-desktop/node_modules/electron-chromedriver
Output:
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/georghartmann/Downloads/webtorrent-desktop/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:378:20)
    at module.exports (/Users/georghartmann/Downloads/webtorrent-desktop/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/georghartmann/Downloads/webtorrent-desktop/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:485:26)
    at ClientRequest.emit (node:events:390:22)
    at ClientRequest.origin.emit (/Users/georghartmann/Downloads/webtorrent-desktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:502:22) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip',
    href: 'https://github.com/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
      statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
      errorCodes: Set(8) {
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      }
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Fri, 12 Feb 2021 17:22:39 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '1; mode=block',
    'referrer-policy': 'no-referrer-when-downgrade',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'set-cookie': [
      '_gh_sess=lDOhFXPY7IY%2FMkkiZF1E%2FFcdS5mUzQOuvEoUzbYYvWMXtXlvQeo5O5NtfYnJDfxE%2F8PI7keonqQqxoQQZA3wMFSBRfmqq7pp8AKPrC6cA8yjDCVWSeRMOweZH7ToolRFwiyXfzaUDD1c%2BG6L3gKfFp7L%2FB5EiPMk88iVfGAfYTFI6fNn0Nz390r%2Bcu77m0GbZBx4bqnrhPxwrwxIInCPWnGeDpWdnlvBml%2Fx8pNestO%2FvIe72%2BEYG%2ByXmLchbyiHgUQHF4viWpxCLlH94kOhPw%3D%3D--LkRDT5KXTId0RhRn--ARwFa51INZOjg3DtVFbrlg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax',
      '_octo=GH1.1.1191868951.1613150559; Path=/; Domain=github.com; Expires=Sat, 12 Feb 2022 17:22:39 GMT; Secure; SameSite=Lax',
      'logged_in=no; Path=/; Domain=github.com; Expires=Sat, 12 Feb 2022 17:22:39 GMT; HttpOnly; Secure; SameSite=Lax'
    ],
    'content-length': '40',
    'x-github-request-id': 'FF31:5164:38F82E:5B1FDD:6026B95F',
    connection: 'close'




```

**Comment by slayerjain** [comment]
@brasilikum any luck getting this to build?

**Comment by brasilikum** [comment]
@slayerjain No. I fiddled around with it a little but I am not familiar for the complexity of electron.

**Comment by slayerjain** [comment]
I tried but faced this problem - https://github.com/webtorrent/webtorrent-desktop/issues/1923

**Comment by fishcharlie** [comment]
As far as I can tell, @feross's commit on November 16th 2020 (https://github.com/webtorrent/webtorrent-desktop/commit/b5fad54f4a42410479a0023d78e84d9fe766e6b4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), upgraded to Electron 11, which [adds support for Apple Silicon](https://www.electronjs.org/blog/apple-silicon/).

It looks like the only issue now is the build process (https://github.com/webtorrent/webtorrent-desktop/blob/master/bin/package.js)? And the fact that there hasn't been a release in over a year?

I'd be happy to try to spend some time to help push this forward. Just let me know.

**Comment by Pepe424** [comment]
How is going? Get someone working native version on Mac?

**Comment by gingergeek8192** [comment]
I came across this issue while working on WebTorrent Desktop and have now put together a working native arm64 Apple Silicon build.

I'm currently running it on an M4 Pro. The build is available here:

https://github.com/gingergeek8192/webtorrent-desktop/releases

The current build is unsigned.

The main changes involved upgrading Electron from 27.3.11 to 39.8.10, replacing the deprecated packaging/signing/notarization packages with their current @electron equivalents, and making several dependency and pnpm compatibility fixes.

If there is still interest in getting Apple Silicon support merged upstream, I'm happy to work on preparing the changes for a PR.

**Comment by tommyent** [comment]
@gingergeek8192 if you or anyone else is interested. I rode shotgun for most of this and planned to look into airplay tonight but after looking through all the pull requests, I don't see any of these being merged. I use a modified version of the CLI so it doesn't matter to much to me.  

https://github.com/tommyent/webtorrent-desktop/tree/modernization/electron-43-webtorrent-3 

| Area | modernization/electron-43-webtorrent-3 | Downloaded snapshot |
|---|---|---|
| Declared version | 0.24.0 | 0.24.0, directory name 0.25.0 |
| Electron | 43.2.0 | 39.8.10 |
| React | 19.2.8 | 17.0.2 |
| WebTorrent | 3.0.16 | 1.9.7 |
| Main UI | Bundled with esbuild | Babel-transpiled CommonJS |
| Main window | Sandboxed, context-isolated, preload API | `nodeIntegration: true`, isolation disabled |
| About window | Sandboxed, no Node globals | Node-integrated with `@electron/remote` |
| Hidden torrent engine | Deliberately privileged | Privileged, as are the other windows |
| IPC | Sender checks, semantic APIs, constrained filesystem paths | Broad renderer IPC and direct Electron/Node access |
| CSP | Restrictive CSP on main and About pages | No CSP; inline `require()` in `main.html` |
| Integration framework | Playwright | Deprecated Spectron |
| macOS packaging | Universal by default; validated arm64, x64, universal | Architecture supplied manually; workflow does not request ARM64 |
| Lockfile/CI | `package-lock.json` + `npm ci` | `pnpm-lock.yaml`, but workflows run unlocked `npm install` |

**Comment by 1337Core** [comment]
If this doesn’t get done by September, WebTorrent Desktop won’t work on the latest macOS version (Golden Gate). Given how long this has been unresolved, I’m starting to lean toward forking it and fixing it myself. As mentioned earlier in this thread, people are already doing that. It just feels sad that it’s come to this.

**Comment by tommyent** [comment]
Some of what I have seen with the forks/PRs Electron and Node versions are EOL; Spectron is deprecated; artifact upload v3 is retired. A lot of the remaining dependencies are stale or superseded.

**Comment by gingergeek8192** [comment]
@1337Core
@tommyent

I’ll be signing and releasing my ARM‑native version in the coming weeks. I’ve run my build for over a week now and it works flawlessly.
The remaining issues ESM migration, dependency cleanup, security patches will be taken care of in due course.  
The first release will be my current unsigned build, notarised.

**Comment by gasp** [comment]
I'm maintaining a fork aimed at keeping WebTorrent Desktop alive long-term on modern macOS: https://github.com/gasp/webtorrent-desktop

It's rebased onto @gingergeek8192's arm64 work (thanks — solid base). On top so far: a fix for `pnpm install` on Apple Silicon (the dead Spectron stack's postinstall scripts break it — happy to PR that to your repo), and a phased roadmap in [MODERNIZATION.md](https://github.com/gasp/webtorrent-desktop/blob/master/MODERNIZATION.md): staged Electron 39→42, native arm64 builds, webtorrent 3.x, contextIsolation, Playwright tests — much of it informed by @tommyent's electron-43-webtorrent-3 branch, which I plan to mine commit-by-commit.

If you'd rather consolidate efforts than run three parallel forks, I'm in.
