### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1936]
**What version of WebTorrent Desktop are you using?**

0.24.0

**What operating system and version?**

All.

**What happened?**

From WebTorrent Desktop telemetry logs:

```
Processes: window, platforms: darwin linux win32, versions: 0.20.0 0.21.0 0.23.0 0.24.0
TypeError: Cannot read property 'status' of undefined
    at TorrentListController.toggleTorrent (.../build/renderer/controllers/torrent-list-controller.js:120:24)
    at .../build/renderer/controllers/torrent-list-controller.js:179:12
    at Array.map (<anonymous>)
    at TorrentListController.resumePausedTorrents (.../build/renderer/controllers/torrent-list-controller.js:178:39)
    at EventEmitter.<anonymous> (.../build/renderer/main.js:375:61)
    at EventEmitter.emit (events.js:322:22)
    at Object.onMessage (electron/js2c/renderer_init.js:90:818)
```

**Comment by alxhotel** [comment]
**Steps to reproduce bug**:

1. Add a torrent that can be streamed (played)
2. Click on the `play` icon of the torrent
3. While on the player screen, click on `Transfers` and then click on `Remove all from list`/`Remove all data files`
