### ISSUE TITLE
malformed config.json crashes app

### ISSUE THREAD

**Issue by mixmix** [webtorrent/webtorrent-desktop#2097]
**What version of WebTorrent Desktop are you using?**)
0.24.0

**What operating system and version?**
Kubuntu LTS

**What happened?**
Webtorrent was working, but had some playback issues streaming a torrent. I tried to restart it and it failed to show any window. In `htop` I observed a WebTorrent process was running. I killed it and tried restarting in terminal and I got this error

```
➜  Downloads webtorrent-desktop 
(node:1284786) UnhandledPromiseRejectionWarning: JSONError: Unexpected end of JSON input while parsing near "...\t\"systemArchitecture\"" in ../.config/WebTorrent/config.json
    at module.exports (/usr/lib/webtorrent-desktop/resources/app.asar/node_modules/application-config/node_modules/parse-json/index.js:29:21)
    at parse (/usr/lib/webtorrent-desktop/resources/app.asar/node_modules/application-config/node_modules/load-json-file/index.js:15:9)
    at module.exports (/usr/lib/webtorrent-desktop/resources/app.asar/node_modules/application-config/node_modules/load-json-file/index.js:18:47)
    at async ApplicationConfig.read (/usr/lib/webtorrent-desktop/resources/app.asar/node_modules/application-config/index.js:18:14)
    at async EventEmitter.load (/usr/lib/webtorrent-desktop/resources/app.asar/build/renderer/lib/state.js:206:15)
(node:1284786) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1284786) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by mixmix** [comment]
went and found that `config.json` file, deleted it, and webtorrent starts up fine!

```
Missing config file: Creating new one
init: 1034.125ms
```

**Comment by mixmix** [comment]
I kept a copy of the corrupt `config.json`, please get in touch directly if you'd like a copy, it has torrenting info baked into it?!
